[[GDB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2952a2be6861aad8b44da963105965e57a75a3f6"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "1bcb273f32393814f63e979134e1cf4a2b8359bbaf5d6fb39c2ff37f09530e26"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7ee3d6f2eb687ece0e1f03da34de4d51495a193"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "0744d9ddd1ffe097e6824c3820a76fccfae200c40bc6d9b34ce1a09ef40a0466"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e56128783f77b5384f91210975fb07f99c22786"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "6769db40da344d573cfbfad07f7cc9ed89ab958c592f85a2d89d90de44605efb"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5894ee6fe2e385e984582779f51603171614bade"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "b68c559512e59228d7c01aa931f9189444b203c0fd5a2b983fe7790ee900ee88"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35f919687f4cac2ec805186fbd094deb36c72baa"
libc = "musl"
os = "linux"

    [[GDB.download]]
    sha256 = "fef6753ec634368a0f7b8049082844d39c82db6b4ff0031a591d255e74adbe61"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9ead760b0f5d8de985c3a9e50fa732a09c66044"
libc = "musl"
os = "linux"

    [[GDB.download]]
    sha256 = "b1c497b4c885c1ef94060885a5a53dc278960cae8805d1f7e28366fc096b0b65"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dee132ba6f212b05ed9f8c65a37e8fdae0d71b6a"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "e34c2cbcf914a75277a53551e8203930d49dd030c319c47fb5d0fbc38684eab2"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.i686-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "915fb7cb3639a8329d10ed9b739b7d03df330585"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "b37b7d355b9bf7fc42490ce3fb5769cc90ca2db83d4327acc353c19191fca3fd"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.i686-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c9e1cacc316c5725894f3d2df9acb015b0cf50d"
os = "windows"

    [[GDB.download]]
    sha256 = "5786954a623d438ea0b5cc80383e7f79b7bb86c65f68947a52b10091f2a2f3d7"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6adcdf7f6100eb28ed1a400473e322abfa87043"
os = "windows"

    [[GDB.download]]
    sha256 = "f3184413a3e1dc38cde1d2cbbe81365363c39c76aaec0062de8c317e6eb79924"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "827d9eb51be07a12b23b363f5d9a4306c60dec92"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "e62b0847946c60bc07cae9eb933133d467e72ca0187ae87001003f23c2393df7"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1c73419785191fc82a41a2e149edd35e9b8a830"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "b91712321bd7324a9ef4f57714573474b6a91cdfd759f1bc0d1386e79e64fa1b"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5435d00db5df3e3ffca70790bb7aa1ab8efe0699"
os = "windows"

    [[GDB.download]]
    sha256 = "69039634798d942a8c4c85c0eb7d421f2e1dcf60d5b2c683557b0c8219803048"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f025bdd44e8754f5a7375f4879d3a7fa3c61d170"
os = "windows"

    [[GDB.download]]
    sha256 = "1e31a244c6f7a447c286f2e5f36acdaac59e4c0d884874d853a2fce864539d88"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.1+0/GDB.v12.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
