[[GDB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ecca9be2e11b214d43f0f4278959693d011222e"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "5e0067525137235c5c0b55d097f8d3a96447d7ce90bf61078a947b0fc2e9434f"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f1af0a9627643a28c2af43d898941dc65ba0bea"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "a225d4b3aef42b86f6ed4e636c93e373515ad96b8fb3cc0c27f8210d49cc070f"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "558bb4e20c52b7851bef2a61ca9e1aeb4b722212"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "15fe4c2d2382de4c1aa730aa453b17b965abf51442ca126ef1edcc63249900c6"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "072abc2306238a491fa40304eff5a0797cc71479"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "f4d5a95cb209d6e01b6f8508dee53deea925573db756e9c1fd24d08c5d102922"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9466e09c66ba9f929488ff3d109c0b28ed368833"
libc = "musl"
os = "linux"

    [[GDB.download]]
    sha256 = "b71b93eb04f83aa7768ec9075fa8883775bbac3b1f3b3cba84cfb8b51cf2cc4c"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1801c2510fb2cd1dbb385e4c820f9378e5bee3e0"
libc = "musl"
os = "linux"

    [[GDB.download]]
    sha256 = "40190b83e75c574677193d7b1162e6056d97a64bdc0d9b65d241e606bc81d80a"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f13072d8a17c03e6b6b05cf9acb5589d75f17d12"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "3bd8a29ddf16e7add58449913b4f49e8542af9e4f129fe67ade42d1af90ef7f0"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.i686-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44b7028263ee20cba8edb04cd5f754118daf6737"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "36e846a1b6cb378877c8fb095eea5a0b0016a79bab3e02ffe3112bb2137b1039"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.i686-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "468dde7d6607311c50341b739da089133eb19622"
os = "windows"

    [[GDB.download]]
    sha256 = "d35eea614c2cc621518fd9b596270f5f9c2724068651febb72a7aab1551be29b"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c2d6cf1f72aa0d6b0564398452aab0de78a1655"
os = "windows"

    [[GDB.download]]
    sha256 = "54e8ca25505ce16a9f021866142c7bf522b12c1c444d15a6e21f406fc874c37d"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e758267d9b9d66c8e97b8dc5a4383c871ca4d7e7"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "218396dbd4bd3e8752f6c355e129f85c1aaf8d267a3d64342e8ca6641c47d38c"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9914dc273df5362d446fab6183a1c674185bb279"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "f8d27fe1a3845ef643728b35fe6ce1c6d5b42e631d07f47e79d268456505cb53"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "069af69f3ee5b24d9e8979351220b84e0ade95e0"
os = "windows"

    [[GDB.download]]
    sha256 = "23ee36eb40b10cfe20357fad99f596e5c933a56d57127d5b561775e884463938"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70489260d32843acf2019d2022c40e4dccd8d586"
os = "windows"

    [[GDB.download]]
    sha256 = "e5961fe071d9c1217043c6b3172a59b4745c834aee7e41ff3b37adc4576e3f29"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+0/GDB.v12.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
