[[GDB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cdb99cd9c35720a468cc13a0fd8bc4dbbe55fe8"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "1b56e466e97f015f1373915b4158635facfb51c61773cf839d06c278143524c4"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2a563ea07f7864d40e4145ae6a251a7edd869f0"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "7b8d9dd4a5f2c8ac8066a7e04b320bca4d94925db78522ed43632ff62fbcd13e"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "880b02079850a495f47e51cb89d274cc16652ca0"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "35862c2f21b85eccbd94b538ec7c1044db17a0e5621afbdce447235e0f6cb137"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1ea37c10b2cd3f4c4802a043b8379d6c176b10e"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "f0fbf8c2cd108005924fdfc196bf3150f4009f2c4d49dfd27c253d61981a05f5"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e533d09706c713327ac4368a7962ff36048e9f8"
libc = "musl"
os = "linux"

    [[GDB.download]]
    sha256 = "021a058f3a33361992175dc3d24eef4c4403d4f3097b2dfb85599d629076de33"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccffbe030bea643b37fba35eae146142781b805e"
libc = "musl"
os = "linux"

    [[GDB.download]]
    sha256 = "0ee5cdf076ce82fc37b5c054aa9e89df6d30e8a3f81ea471fb48130ab6d426c6"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a60e0d8845b7ba6c248e31e6a54a84cc7bd5ba58"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "e34f4cfaccd5bb5cc95178486998386a94c215421c7515113248941d2b6d0621"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.i686-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fa421c09b93e0f2e8c0ea6becf031076f590a81"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "23a04ce31689f3882e392bfabc0338dac7caf096cca38929a927095d81f9d468"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.i686-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15dfcb9b3d760f6a036ed0bde883e5bc1f37f681"
os = "windows"

    [[GDB.download]]
    sha256 = "a27ae6d6ca0b07fd4d2d5f4dccd3bad213f0d3f6fa23c7d9540440be8ea76f7a"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88453a2d564d8f2d0d50832a1aca643ae93026c2"
os = "windows"

    [[GDB.download]]
    sha256 = "07bd4f3a11e73886ffbac6f15379b9a1a499bcd9da064e31ea13be0c595fc545"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "724d9bc1d493875b7999b9f8eccb10a368ad5311"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "51545b6fb66fddaf64fbc409353f02fd2413e0873595963b549eda1e9aff00dc"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d2f6b6f4f4cb56741ee630fbec4d86be20cbab7"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "bbece8e7418212dc9b122d0d0bbbbdcf34d1954bc531f7fa404abdf8ece8af4c"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5879f238f5f8b4fac51423e3be81e0872bb3721d"
os = "windows"

    [[GDB.download]]
    sha256 = "96f22debd45d0d8f9e3aebf25e123c83569c5e971cab7b8901561ef3f8df7085"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f10b9498a95104f606de5b93d5e9d32840bc91d"
os = "windows"

    [[GDB.download]]
    sha256 = "451b95bd0ee97fc63c7eddefdd26512ae082ca1df2d961cb632e9e02794d9b8d"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v12.1.0+1/GDB.v12.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
