[[GDB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39db0e460e37e206b10849655e4d6e522abd2224"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "2f4bb68876cdbf03dfdb02cbee709491157a0c85e4d3227c3a087e4985656bf1"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c575be477e02d6d03dce9a9e17ff93d1ad07814"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "75c462b98c0c97fe1dd654729d3dcaf4b9232842ff8c5af336d34c1cfcdf85e6"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "daba90b6ff04df7e86bc1591d4803a5aba6f3aa0"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "077ebe898721ef4133772c1491a7d3bf60334f49449377fb406d635cf4c488bd"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd343155a1f56dd629f9d7d662489beca7d44f45"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "1728461e83e791a3a75ec3b9409311036271cb3ba7c9f500df8bb03654745b82"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49f840a921a838cd780e6ad64da52427bcc219b3"
libc = "musl"
os = "linux"

    [[GDB.download]]
    sha256 = "31340a2dda45e545d8518660fa9c4df0803a9e4d45b565ca3c7c6fd5dde2dce9"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27522d408fd679b3e0954a317f0fb7815846cb9e"
libc = "musl"
os = "linux"

    [[GDB.download]]
    sha256 = "f762d9015fa79731f493d8a3564cf6033cd62a071e2931a60fb33ec0eb5df788"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e5c66643e084c12f7cfbb0ad8bd07dabc770328"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "8e19c92761860850f79063849c8ca28597e774e68df092b9d3bb702543c25953"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.i686-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce130ea0e5d4bf2cd2b097f6755ce3bcae8b0e59"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "57e30ba47c59d679677bf5ae73a8944b247d9c90bd675c8921c20ce001b0d041"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.i686-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7133778fa129ae8015f98e24282fc49db9385791"
os = "windows"

    [[GDB.download]]
    sha256 = "fd1a4104d6537fe31d905cbe6a78bc71d308b596fe8c0ce4bab01a9dd44e2535"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[GDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14d5f114b949c89de0b6f2871bb4ed4aa2b3ac01"
os = "windows"

    [[GDB.download]]
    sha256 = "7562db522258abc9802a7ff4d2291ea0eee7be94b7d35e632c2336e3e031f684"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ea676cee222a6d7ca476796c1b950521bc682da"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "a48b3478f3e4fc99fa973ede0b546f059855f25913a24cc7303084e3d89a48d8"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "723ff26494de42b0a088c6c0a326085b7792c803"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "d40830f35279480225367ec05044c0eb8216319246deebe1a2bf9e809c7c9d5f"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53c72bbaa99f805b031faf991a8335460a10738d"
os = "windows"

    [[GDB.download]]
    sha256 = "ab894b2f75273bdc77ad120f567a0f370399e36ca1b4666d2955da17dc340e35"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3e21812fb58f17f50781d4c86d2faa6da5ec66e"
os = "windows"

    [[GDB.download]]
    sha256 = "7d8138e41cbd455feef503397de18abaa9be105d59db7a5bc97f2c22f8e1012f"
    url = "https://github.com/JuliaBinaryWrappers/GDB_jll.jl/releases/download/GDB-v10.1.0+1/GDB.v10.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
